version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    command: mongod --bind_ip 0.0.0.0

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongodb:27017/url_shortener
    depends_on:
      - mongodb
